# Generated by Django 4.2.2 on 2023-06-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='static/media/'),
        ),
        migrations.AddField(
            model_name='chatmessages',
            name='media_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
